### ISSUE TITLE
Griefdefender support wont work

### ISSUE THREAD

**Issue by timr2000** [BG-Software-LLC/WildInspect#19]
### Minecraft's Version

purpur 1519

### Plugin's Version

2.3.5.26

### Describe the bug

Players can check blocks in wilderness and admin claims or other claims without trust

### To Reproduce

Just try it out yourself with griefdefender

**Comment by OmerBenGera** [comment]
What is your discord?
I need you to send me a copy of the plugin so I can test it.

**Comment by timr2000** [comment]
My discord is timr2000#0001

> What is your discord? I need you to send me a copy of the plugin so I can test it.

**Comment by timr2000** [comment]
> What is your discord? I need you to send me a copy of the plugin so I can test it.

My discord is timr2000#0001

**Comment by OmerBenGera** [comment]
Does it still occur?
