### ISSUE TITLE
Coreprotect v21+ breaks WildInspect results

### ISSUE THREAD

**Issue by SmallSansSerif** [BG-Software-LLC/WildInspect#21]
### Minecraft's Version

git-Purpur-1566 (MC: 1.18.1)

### Plugin's Version

WildInspect version 2.3.5 #27

### Describe the bug

No results returned using v21 vs v20 of CoreProtect.

### To Reproduce

Load up v21+ of CoreProtect, try to see inspect results from WildInspect.

### Additional Information

Thanks for the Towny hook update!

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
