### ISSUE TITLE
npc of spawn doesnt work

### ISSUE THREAD

**Issue by Gregoryxnmasd** [BG-Software-LLC/WildInspect#23]
### Minecraft's Version

1.19.2

### Plugin's Version

1.11.1-b772

### Describe the bug

i cant interact to my the npc´s that are in the spawn because it says that this island is protected but it is another world separated from the skyblock world cause is the spawn and it says to me that if i want to interact to the npc i have to put /is admin bypass but i dont want to put that command cause it will grant access to other people to bypass all

### To Reproduce

click to an npc of the spawn

**Comment by OmerBenGera** [comment]
Not related to the plugin.
Ask for help in our discord.
