### ISSUE TITLE
Hide operators

### ISSUE THREAD

**Issue by Morphiee** [BG-Software-LLC/WildInspect#24]
### Minecraft's Version

1.19.3

### Plugin's Version

2.4.1

### Describe the bug

When set to true in the config. It does not hide players marked as operator from the inspection.

### To Reproduce

Have an operator break a block. Have a player inspect broken block. Player can see that the operator broke the block. (this is with the hideops config section set to true)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still persists let me know
