### ISSUE TITLE
[GriefPrevention] Players can inspect on others claims

### ISSUE THREAD

**Issue by Tosfoy** [BG-Software-LLC/WildInspect#28]
### Minecraft's Version

This server is running Pufferfish+ version git-PufferfishPlus-"a9f972b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)

### Plugin's Version

WildInspect: 2.4.1 & Dev Build #2
CoreProtect: 22.2
GriefProtection: Latest dev build

### Describe the bug

Players are able to inspect in others claims
No errors in the console

### To Reproduce

Install all three plugins

**Comment by OmerBenGera** [comment]
I am using latest versions of all plugins and cannot replicate the issue.
Maybe you use `/co inspect` instead of the plugin's inspect command (Configurable)?

**Comment by Tosfoy** [comment]
We are using the right command, which by default is /f inspect.
I'm going to try seting up a server with only these 3 plugins and nothing else, I'll see what happens.
