### ISSUE TITLE
Support Core Protect 23

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildInspect#34]
### Minecraft's Version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-27T06:45:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.4 

### Describe the bug

It should work with Core Protect 23 as it is the only build that support 1.21

### To Reproduce

use coreprotect 23 https://www.patreon.com/posts/coreprotect-v23-113032756

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by YusakiDev** [comment]
It is fixed.
